### PR TITLE
Add dask-cudf 

### PR DESCRIPTION
**Pull request by quasiben**
PR adds dask-cudf to the API section of https://docs.rapids.ai/api .  Follow up PR for https://github.com/rapidsai/cudf/pull/12725 and https://github.com/rapidsai/cudf/pull/12982

cc @wence-

### CODE REVIEW

**Review by sevagh — APPROVED** [review]

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
We shouldn't merge this yet.

Although there is a corresponding PR to `cudf` here: https://github.com/rapidsai/cudf/pull/12982, the docs that are generated by GitHub Actions are not actually used by the docs website quite yet.

So merging the `cudf` PR above does not imply that this PR can be merged and the `dask-cudf` docs will show up on the docs site.

The docs that are published on our website are generated by a Jenkins job and committed directly to this repository.

We will eventually remove the docs that are committed to this repository and configure our website build process to build the HTML files from S3.

Until that work is done, we will need to add `dask-cudf` to our Jenkins-based doc build process before we can merge this PR.

**Comment by ajschmidt8** [comment]
> @ajschmidt8 should we merge in [rapidsai/cudf#12982](https://github.com/rapidsai/cudf/pull/12982) and then ping for a jenkins build ?

Yup. No harm in merging https://github.com/rapidsai/cudf/pull/12982.

**Comment by ajschmidt8** [comment]
Closing this PR for now.

See https://github.com/rapidsai/docs/issues/360 for details.

**Comment by ajschmidt8** [comment]
superseded by: https://github.com/rapidsai/docs/pull/365

**Pull request closed without merging**
