### PR TITLE
Link assets instead of inlining them (w/ docs)

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR includes the following changes with the docs re-processed:

- Changes the customization script to include a link to remote CSS/JS assets instead of inlining them
   - Updates docs to reflect this change.
- Move contents of `rapids.js` and `rapids.css` into `assets/` folder and delete original files
- Minor css tweaks to adjust scoping
- Makes all paths relative
- Removes `<script>` tags that reference non-existent files

### CODE REVIEW

**Comment by ajschmidt8** [comment]
https://5e74d1cc088f4784bf83a87d--docs-rapids-ai.netlify.com/

**Comment by exactlyallan** [comment]
Docs are looking really good - I had fun just clicking around! Much much better than older ones. 
Few minor points I noticed:
- Home Button not left aligned ( intentional? )
- On mobile RTD nav bar is blue ( change to purple or change text to white )
- On mobile doxygen, nav needs left padding ( Home button not left aligned ?)
- On doxygen, widen underline to full button, maybe add few px margin under so underline does not blend into nav bar below and hover-over effect is more visible

**Comment by ajschmidt8** [comment]
- [x] Home Button not left aligned ( intentional? )
- [x] On mobile RTD nav bar is blue ( change to purple or change text to white )
- [x] On mobile doxygen, nav needs left padding ( Home button not left aligned ?)
- [x] On doxygen, widen underline to full button, maybe add few px margin under so underline does not blend into nav bar below and hover-over effect is more visible

should be all set! changes should be reflected in the preview environment shortly.

**Comment by exactlyallan** [comment]
@mike-wendt Looks much better, I like the font hierarchy. One suggestion is to make the separator | the same font weight and color as Docs/Links text.

**Comment by ajschmidt8** [comment]
@exactlyallan, please check out the latest deploy preview to see if everything looks okay 👍

**Pull request merged**
